def new_prefunded_account(address, private_key):
	return struct(address = address, private_key = private_key)

# This information was generated by:
#  1) Installing Wagyu: https://github.com/AleoHQ/wagyu
#  2) Running `wagyu ethereum import-hd -m MNEMONIC_FROM_GENESIS -d PREFUNDED_ACCOUNT_DERIVATION_PATH`
#  3) Copying the outputted information
PRE_FUNDED_ACCOUNTS = [
	# UTC--2023-03-06T13-12-14.958269881Z--10e51d95207128cc1c8e4bc0fdbfb97e530e57b3
	# m/44'/60'/0'/0/0
new_prefunded_account(
		"0x10e51D95207128cC1C8E4bC0FdBfB97e530E57B3",
		"b1295b704d59e8cf886ccbe7f08b4430d695e265c9a3b84f457ab3f3e1ba2bf1",
	),
	# UTC--2023-03-06T13-12-22.322527119Z--9cd948cb92e16864f9b56161f36cac5f9b7cd33a
	# m/44'/60'/0'/0/1
new_prefunded_account(
		"0x9CD948cb92E16864F9b56161f36CAC5f9B7cd33A",
		"046e438061dad3931932d6f03e9f6cf92b495b5a99440d08be2b5a3817781e28",
	),
	# UTC--2023-03-06T13-12-32.775134532Z--a010d04a5e14d751b73ac5b6b3f287972575240
	# m/44'/60'/0'/0/2
new_prefunded_account(
		"0xa010D04A5e14D751b73aC5b6B3F287972575240e",
		"0dacb19de0e946f74b8d0890e95729c41aff04202edc5c6cdbfcf692dff2ce23",
	),
	# UTC--2023-03-06T13-12-38.642923882Z--ac0ac6533c502b6494b498b19e007d0212528a90
	# m/44'/60'/0'/0/3
new_prefunded_account(
		"0xAc0aC6533c502B6494B498b19E007D0212528a90",
		"ad06b7947305fd2b3971fb1f63419bcd562689d62ee2bdd9c565bc146a9ec6ef",
	),
	# UTC--2023-03-06T13-12-50.453187451Z--99fc8022bb30aa83038f62379fba9da041407adb
	# m/44'/60'/0'/0/4
new_prefunded_account(
		"0x99FC8022bB30AA83038f62379fBA9DA041407ADb",
		"57f882a0dbb2571f462030828446ac95ab91ad541fba423b0becfff7398a1737",
	),
	# UTC--2023-03-06T13-12-59.213391699Z--79a27f1b02541c049919e68a69dfacc5b18cac2b
	# m/44'/60'/0'/0/5
new_prefunded_account(
		"0x79a27f1b02541C049919E68a69DFaCc5B18CAc2B",
		"d150d57f4e0ddfb25973d55197c0ef6eaffd507f374439dd4aefca87b04ad6f5",
	),
]
